site_name: Skit Tech Curriculum
repo_url: https://github.com/skit-ai/curriculum

nav:
    - Introduction: index.md
    - Part 1:
        - building/index.md
        - building/01.md
        - building/02.md
        - building/03.md
    - Part 2:
        - deploying/index.md
    - Part 3:
        - misc/index.md
        - misc/01-parsing.md
    - Part 4:
        - misc/np.md

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - meta

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  palette:
    primary: white
    accent: cyan
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - navigation.instant
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/school
    favicon: fontawesome/brands/git-alt
